### ISSUE TITLE
Support for Array types

### ISSUE THREAD

**Issue by Soviut** [topliceanu/mongoose-gen#10]
The documentation is scarce explaining how to store arrays. I've assumed the "Mixed" type is what to use.

Mongoose seems to support "Array" and "Object".

**Comment by topliceanu** [comment]
Hi @Soviut. Yes mongoosejs does support Array and nested Object types. Here's what I think you mean:

```js
var BlogSchema = new mongoose.Schema({
  'comments': [{
    'text': {type: String}, 
    'thumbsUp': {type: Number}
  }]
});
```
And so does mongoose-gen, here's a [test with arrays of objects being defined](https://github.com/topliceanu/mongoose-gen/blob/master/test/generator.js#L234). It's pretty much the same thing with nested objects. Let me know if you hit any bug!

**Comment by Soviut** [comment]
Ah, that's close. I need one property to store an array of strings and another property to store and object to act as key/value pairs.

```coffeescript
key:
    type: 'String'
    unique: true
    required: true
parents:
    type: 'Array' # array of strings
    required: true
values:
    type: 'Object' # key/value pairs
    required: true
```

**Comment by topliceanu** [comment]
It should work. Note that, like this, there is no way to enforce `parents` to only contains strings.
Let me know if it doesn't work!

**Comment by Soviut** [comment]
So the following won't work?
```coffeescript
parents: [
    {type: 'String'}
]
```
Should I just be setting the parents array like so
```coffeescript
parents: []
```
And in doing so, how can I set things like `required`?

**Comment by Soviut** [comment]
Also when I use the following:
```coffeescript
parents:
    type: 'Array' # array of strings
    required: true
```
I get this error:
```
Error: unknown type Array
  at matchType (P:\Projects\CopyDeck\api\node_modules\mongoose-gen\lib\generator.js:103:11)
```

**Comment by topliceanu** [comment]
```js
parents: [
    {type: 'String'}
]
```
This ^^ works as exemplified by the test above.
As per the `Array` type, that is a bug! I'll come back with a fix shortly. 10x

**Comment by topliceanu** [comment]
`v2.0.1` published, it was an easy fix. Will add some examples on using nested objects and arrays. 10x

**Comment by Soviut** [comment]
Great, I'll take it for a test drive in a bit.

**Comment by Soviut** [comment]
@topliceanu I've finally had a chance to test this but I'm still getting an error. The issue is with my array field:
```coffeescript
parents:
    type: 'Array'
    required: true
```
The error I get is:
```
ValidationError: Path `parents` is required.
  at Array.forEach (native)
```
I realize this is a validation error from mongoose, but at this point, I'm documenting my progress.

**Comment by Soviut** [comment]
Ive filed a bug with Mongoose https://github.com/LearnBoost/mongoose/issues/2662
