### ISSUE TITLE
support `type: 'object'`

### ISSUE THREAD

**Issue by jon49** [topliceanu/mongoose-gen#14]
I found the project `Clever/json-schema-converter` to be a stellar project, unfortunately it doesn't look like the author is supporting it anymore. `mongoose-gen` appears to be clean, supported, and active. So, I guess I would like many of the features in `json-schema-converter` to be supported in this project. I'll see what I can do to get help this project move closer to `json-schema-converter` in capability.

I guess I would like to start with support of `type: 'object'`.

**Comment by jon49** [comment]
It looks like, in order to support objects we would need approach the code with a recursive function instead of `JSON.parse`. Maybe I should just fork `json-schema-converter` and fix its issues since it is almost there.

**Comment by topliceanu** [comment]
created branch `14-support-type-object`

**Comment by topliceanu** [comment]
@jon49 You are right, the `type: "object"` was not supported. I have added it and you can now use it. You can see the code [here](https://github.com/topliceanu/mongoose-gen/pull/15/files). Hope this helps.

However, I should say the mongoose has a special type called `Mixed` which `mongoose-gen` supports and which might be what you are looking for. In the mongoose docs, users are adviced not to use `type: 'object'` directly, instead use a nested object in the schema definition. Again, this feature is supported by `mongoose-gen`.

https://github.com/Clever/json-schema-converter looks great. starred it! are you specifically interested in converting JSONSchema into mongoose.Schema object?

**Comment by jon49** [comment]
Yes, I'm looking to convert json-schema to mongoose.Schema. What I'm specifically doing is taking TypeScript, converting it to json-schema (with typson) and then I'm wanting to use that to convert to mongoose.Schema. This way all my types can be under one "roof" and I can do validation (with is-my-json-valid), schemas (with yours or json-schema-converter, which ever I can get all the bugs out first), filtering (with is-my-json-valid), and documentation (with docson). It's pretty nice. All the work everyone has put into this is just amazing, it would take me forever to do all that work.

**Comment by jon49** [comment]
Just looked at what you did. I guess what I should have been requesting is the ability to have a recursive object (with specific types). Right now it seems to be just flat. But thanks for taking the time to look at it.

**Comment by topliceanu** [comment]
Hei @jon49 `mongoose-gen` does support nested definitions. Take a look at this [test case](https://github.com/topliceanu/mongoose-gen/blob/master/test/generator.js#L234-L275) for an example on how to use it.

Having `all my types can be under one "roof"` is a cool idea! And, in term of interoperability, i can see JSONSchema as the best choice. `mongoose-gen` however was born out of a different need: store mongoose schemas on disk, so you can generate models out of schemas at bootup!

**Comment by topliceanu** [comment]
... and have other processes modify the schemas as needed!

**Comment by jon49** [comment]
Cool, use case.

I guess I misspoke again. I should say nested definitions with $ref to other definitions. Sorry about that, for some reason I'm just not being as specific as I should.
