### ISSUE TITLE
How are Arrays of DBRefs supported?

### ISSUE THREAD

**Issue by parkan** [topliceanu/mongoose-gen#17]
Hi, I'm trying to use this in a project for translating graphql schemas to mongoose schemas but I can't find a way to use Arrays of DBRefs as per the project description -- only plain `type: Array` seems to be supported, which is an array of Mixed.

**Comment by parkan** [comment]
I see, you can just pass an array for that key, just like in the normal schemas, great! Closing.

**Comment by topliceanu** [comment]
Hi, yeah! There's an example on that too.

On Mon, Sep 28, 2015 at 11:01 PM, Arkadiy Kukarkin <notifications@github.com
> wrote:

> Closed #17 <https://github.com/topliceanu/mongoose-gen/issues/17>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/topliceanu/mongoose-gen/issues/17#event-421276435>.
>



-- 
Alexandru Topliceanu

**Comment by parkan** [comment]
I looked in here for an example but didn't see any: https://github.com/topliceanu/mongoose-gen/blob/master/examples/using-dbrefs.js
