### ISSUE TITLE
schema() returns a model, not a schema

### ISSUE THREAD

**Issue by boneskull** [topliceanu/mongoose-gen#3]
I'm wondering why it works in this manner.  In order to get the schema and attach plugins to it, I have to do this sort of devilry:

```javascript
var data = fs.readFileSync('public/models/user.json');
var User = new Schema(generator._convert(JSON.parse(data)));
User.plugin(somePlugin, {});
module.exports = mongoose.model('User', User);
```

I'm using a private method I shouldn't be using.  If I get the model via ```schema()``` then modifing the model's `schema` property directly doesn't seem to work because the model is already created.

**Comment by topliceanu** [comment]
@boneskull Yes, that was stupid! I upgraded this module, so that you would now do: 

```javascript
var UserSchema = generator.getSchema(JSON.parse(data));
var UserModel = mongoose.model('User', UserSchema);
```

**Comment by topliceanu** [comment]
@boneskull it would be lovely to get some feedback from you for the latest version ;)

**Comment by boneskull** [comment]
Hehe, forgot about this one.  I haven't had occasion to use mongoose in awhile, so I will reserve comment until I do.  Thanks though!

**Comment by topliceanu** [comment]
Cool. 10x
