### ISSUE TITLE
support for Embedded documents?

### ISSUE THREAD

**Issue by Danny-weebo** [topliceanu/mongoose-gen#6]
Me and @israelidanny are building a system using your module.
I see that there is support for referenced documents, however - how do I define embedded documents? Is there any support?

If so, how do I use it?

If not, is there any preferred way to take the development of this module in a fork and enable this feature (syntax, e.t.c) so we could send a pull request.

**Comment by topliceanu** [comment]
Started working on this, development branch is `6-nested-documents-support`
